# Generated by Django 3.1.5 on 2021-01-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='post_auth',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
