# Generated by Django 3.1.5 on 2021-01-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_postdetail_post_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='post_auth',
            field=models.CharField(default='', max_length=50),
        ),
    ]
