# Generated by Django 3.1.5 on 2021-01-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_auto_20210127_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='pic'),
        ),
    ]
