# Generated by Django 3.1.5 on 2021-01-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_auto_20210127_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
