# Generated by Django 3.1.5 on 2021-01-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_postdetail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='post_video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
