# Generated by Django 3.1.5 on 2021-02-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_postdetail_auth_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='other_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postdetail',
            name='other_link_desc',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
